import enum


class TokenType(enum.Enum):
    VARIABLE = "VARIABLE"
    WORD = "WORD"
    NUMBER = "NUMBER"
    STRING = "STRING"
    NEWLINE = "NEWLINE"
    EOF = "EOF"
    ANNOTATION = "ANNOTATION"
    TAG_TOKEN = "TAG_TOKEN"

    # Keywords

    DEFINE = "DEFINE"
    MATCH = "MATCH"
    OBJECT = "OBJECT"
    TRAIT = "TRAIT"
    VARIANT = "VARIANT"
    IMPORT = "IMPORT"
    AS = "AS"
    WHILE = "WHILE"
    FOREACH = "FOREACH"
    IF = "IF"
    THIS = "THIS"
    FN = "FN"
    CALL = "CALL"
    SELF = "SELF"
    PUBLIC = "PUBLIC"
    PRIVATE = "PRIVATE"
    READABLE = "READABLE"
    IMPLEMENTS = "IMPLEMENTS"
    WHERE = "WHERE"
    ABOVE = "ABOVE"
    ANY = "ANY"
    TAG = "TAG"

    # Reserved Concurency Keywords
    SPAWN = "SPAWN"
    AWAIT = "AWAIT"
    ASYNC = "ASYNC"
    PARALLEL = "PARALLEL"
    CONCURRENT = "CONCURRENT"

    # Special Symbols
    AMPERSAND = "AMPERSAND"
    ARROW = "ARROW"
    COLON = "COLON"
    COMMA = "COMMA"
    DOT = "DOT"
    DUPLICATE = "DUPLICATE"
    EQUALS = "EQUALS"
    EXCLAMATION = "EXCLAMATION"
    GREATER_THAN = "GREATER_THAN"
    LEFT_BRACE = "LEFT_BRACE"
    LEFT_PAREN = "LEFT_PAREN"
    LEFT_SQUARE = "LEFT_SQUARE"
    LESS_THAN = "LESS_THAN"
    MINUS = "MINUS"
    PERCENT = "PERCENT"
    PIPE = "PIPE"
    PLUS = "PLUS"
    POP = "POP"
    QUESTION = "QUESTION"
    RIGHT_BRACE = "RIGHT_BRACE"
    RIGHT_PAREN = "RIGHT_PAREN"
    RIGHT_SQUARE = "RIGHT_SQUARE"
    SLASH = "SLASH"
    STAR = "STAR"
    SWAP = "SWAP"
    TILDE = "TILDE"
    UNDERSCORE = "UNDERSCORE"
    WHITESPACE = "WHITESPACE"
