import enum


class TokenType(enum.Enum):
    VARIABLE = "VARIABLE"
    WORD = "WORD"
    NUMBER = "NUMBER"
    STRING = "STRING"
    NEWLINE = "NEWLINE"
    EOF = "EOF"
    ANNOTATION = "ANNOTATION"
    TAG_TOKEN = "TAG_TOKEN"

    # Keywords
    AS = "as"
    AS_UNSAFE = "as!"
    ASSERT = "assert"
    AT = "at"
    CONCURRENT = "concurrent"
    DEFINE = "define"
    ELSE = "else"
    FN = "fn"
    FOREACH = "foreach"
    HANDLE = "handle"
    IF = "if"
    IMPORT = "import"
    MATCH = "match"
    MULTI = "multi"
    OBJECT = "object"
    PANIC_KEYWORD = "panic"
    PRIVATE = "private"
    PUBLIC = "public"
    READABLE = "readable"
    SELF = "self"
    SPAWN = "spawn"
    THIS = "this"
    TRAIT = "trait"
    TRY = "try"
    UNFOLD = "unfold"
    VARIANT = "variant"
    WAIT = "wait"
    WHILE = "while"

    # Special Symbols
    AMPERSAND = "AMPERSAND"
    ARROW = "ARROW"
    COLON = "COLON"
    COMMA = "COMMA"
    DOT = "DOT"
    DUPLICATE = "DUPLICATE"
    EQUALS = "EQUALS"
    EXCLAMATION = "EXCLAMATION"
    GREATER_THAN = "GREATER_THAN"
    LEFT_BRACE = "LEFT_BRACE"
    LEFT_PAREN = "LEFT_PAREN"
    LEFT_SQUARE = "LEFT_SQUARE"
    LESS_THAN = "LESS_THAN"
    MINUS = "MINUS"
    PERCENT = "PERCENT"
    PIPE = "PIPE"
    PLUS = "PLUS"
    POP = "POP"
    QUESTION = "QUESTION"
    RIGHT_BRACE = "RIGHT_BRACE"
    RIGHT_PAREN = "RIGHT_PAREN"
    RIGHT_SQUARE = "RIGHT_SQUARE"
    SLASH = "SLASH"
    STAR = "STAR"
    SWAP = "SWAP"
    TILDE = "TILDE"
    UNDERSCORE = "UNDERSCORE"
    WHITESPACE = "WHITESPACE"
